name: Lighthouse
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://next-tailwind-storybook-git-${GITHUB_REF#refs/heads/}.johnjacob.now.sh
          budgetPath: ./budgets.json
          runs: 3
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: ".lighthouseci" # This will save the Lighthouse results as .json files
